apiVersion: v1
kind: ConfigMap
data:
  database_url: mongo-service
metadata:
  name: mongo-configmap
  namespace: mongo
---
apiVersion: v1
kind: Namespace
metadata:
  name: mongo
  labels:
     app: mongodb
