apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-deployment-nginx
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx
        ports:
        - containerPort: 8080
